version: "3.1"

services:

  python:
    image: python:3.9.18-alpine
    restart: unless-stopped
    container_name: "${PROJECT_NAME}_python"
    working_dir: /app
    command: sh -c "pip3 install -r requirements.txt && python3.9 main.py"
    ports:
      - 19999:19999
    volumes:
      - ./../../:/app

  nginx:
    image: nginx:1.25.4-alpine
    restart: unless-stopped
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - python
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./../../nginx/local/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - ./../../.cert/:/etc/cert
